name: docker-ci

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app .

      - name: Run container
        run: docker run -d -p 3000:3000 app

      - name: Wait for app
        run: sleep 10

      - name: Test application
        run: curl -f http://localhost:3000

      - name: Stop container
        run: docker stop $(docker ps -q)
